/**
 * Auto-generated by scripts/optimize-images.mjs.
 * Do not edit by hand — regenerate by re-running the optimizer when
 * source portraits change.
 *
 * Each entry is a base64-encoded WebP blur placeholder (~16px wide,
 * blurred), embedded into page HTML as a Next.js <Image>
 * placeholder='blur' source. Avoids the empty-container flash while
 * the full portrait loads.
 */
export const portraitBlurMap: Record<string, string> = {
  "dr-amandeep-singh": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAQCdASoQAAkABABoJYwCdAELXOKKwAD+tcmRwj1GvhRKgL0jQXc6IALwAA==",
  "dr-angela-huang": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoQAAkABABoJYwCsAC0vWVzAAD+Z8xgKFxtyyEIXik4Xlu9pmQAgAAA",
  "dr-brien-hsu": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACwAQCdASoQAAkABABoJZQCsADyVfOAAP6zQ/K6+Y6QlfyrfjIAuIkiAAA=",
  "dr-rachel-lim": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAQCdASoQAAkABABoJYwCdAEKnSdMAAD+1oTcIYprd1kYG3yV0gY4VW2gAA==",
  "dr-robert-sharobiem": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoQAAkABABoJYwCdACEwr1cAAD+sVid4yYJkbBNfhoGACGkOqqbgAAA"
};
