/**
 * Image optimizer + LQIP generator.
 *
 * Two passes:
 *   1. Convert PNG sources in `public/` to WebP. Next.js's <Image> still
 *      optimizes further at delivery (AVIF/WebP variants via the loader),
 *      but smaller source = faster cold-cache responses + smaller repo
 *      + faster Vercel builds.
 *   2. For each portrait in `public/images/doctors/`, generate a base64
 *      LQIP (low-quality image placeholder) — a tiny 16px-wide WebP that
 *      embeds in HTML and shows instantly while the full image loads.
 *      Output as a TS map at `content/doctors-blur.ts`.
 *
 * Run: pnpm exec node scripts/optimize-images.mjs
 */
import { readdir, stat, writeFile } from 'node:fs/promises';
import { basename } from 'node:path';
import sharp from 'sharp';

const QUALITY = 85;

const portraitDir = 'public/images/doctors';
const PORTRAIT_FILES = (await readdir(portraitDir)).map(
  (f) => `${portraitDir}/${f}`,
);
const PNG_TARGETS = [
  'public/logo.png',
  ...PORTRAIT_FILES.filter((f) => f.toLowerCase().endsWith('.png')),
];

// ─── Pass 1: PNG → WebP conversion (skips files that don't exist) ──────────
let totalIn = 0;
let totalOut = 0;
let converted = 0;

console.log(`Pass 1: Converting PNG sources to WebP @ q${QUALITY}\n`);

for (const path of PNG_TARGETS) {
  let sizeIn;
  try {
    sizeIn = (await stat(path)).size;
  } catch {
    continue; // already converted in a prior run
  }
  totalIn += sizeIn;
  converted++;

  const outPath = path.replace(/\.png$/i, '.webp');
  await sharp(path).webp({ quality: QUALITY, effort: 6 }).toFile(outPath);

  const sizeOut = (await stat(outPath)).size;
  totalOut += sizeOut;

  const fmt = (b) => `${(b / 1024).toFixed(0).padStart(6)} KB`;
  const ratio = ((1 - sizeOut / sizeIn) * 100).toFixed(1);
  console.log(
    `${fmt(sizeIn)} → ${fmt(sizeOut)}  (-${ratio}%)  ${basename(outPath)}`,
  );
}

if (converted === 0) {
  console.log('  (no PNG sources found; already converted)');
} else {
  const fmtMb = (b) => `${(b / 1024 / 1024).toFixed(2)} MB`;
  console.log(
    `\nTotal: ${fmtMb(totalIn)} → ${fmtMb(totalOut)} (saved ${fmtMb(totalIn - totalOut)})`,
  );
}

// ─── Pass 2: LQIP generation for portraits ────────────────────────────────
console.log(`\nPass 2: Generating LQIP blur placeholders for portraits\n`);

const portraits = (await readdir(portraitDir)).filter((f) =>
  f.toLowerCase().endsWith('.webp'),
);

const blurMap = {};

for (const file of portraits) {
  const path = `${portraitDir}/${file}`;
  // Tiny blur — 16px wide, low effort, low quality. Keeps base64 string
  // under ~2KB so it inlines cheaply in the page HTML.
  const buf = await sharp(path)
    .resize(16, null, { fit: 'inside' })
    .blur(1.2)
    .webp({ quality: 30, effort: 4 })
    .toBuffer();
  const dataURL = `data:image/webp;base64,${buf.toString('base64')}`;
  const slug = file.replace(/\.webp$/, '');
  blurMap[slug] = dataURL;
  console.log(`  ${file.padEnd(34)} ${(dataURL.length / 1024).toFixed(2)} KB inline`);
}

// Write out as a TS module that doctors.ts can import.
const tsOut = `/**
 * Auto-generated by scripts/optimize-images.mjs.
 * Do not edit by hand — regenerate by re-running the optimizer when
 * source portraits change.
 *
 * Each entry is a base64-encoded WebP blur placeholder (~16px wide,
 * blurred), embedded into page HTML as a Next.js <Image>
 * placeholder='blur' source. Avoids the empty-container flash while
 * the full portrait loads.
 */
export const portraitBlurMap: Record<string, string> = ${JSON.stringify(blurMap, null, 2)};
`;

await writeFile('content/doctors-blur.ts', tsOut);
console.log(`\n✓ Wrote content/doctors-blur.ts (${portraits.length} entries)`);
